name: On Push
description: Deploy a python function to aws Lambda. This workflow is triggered on pushes to the master branch of the repository.
on:
  push:
    branches:
      - master

runs:
  using: 'docker'
  image: 'Dockerfile'
