name: On Push
description: Deploy a python function to aws Lambda. This workflow is triggered on pushes to the master branch of the repository.
on:
  push:
    branches:
      - master

inputs:
  requirements:
    description: Space delimited list of python packages to deploy with the function, i.e. 'pandas pytorch pytz'
    required: false
    default: 'pipdate'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploying to AWS Lambda
      uses: samsetegne/py-lambda-action@0.0.5
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_OUTPUT: ${{ secrets.AWS_DEFAULT_OUTPUT }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        LAMBDA_LAYER_ARN: ${{ secrets.LAMBDA_LAYER_ARN }}
